
FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    mlflow==3.7.0 \
    pandas==2.1.4 \
    numpy==1.26.2 \
    scikit-learn==1.3.2 \
    xgboost==3.1.2 \
    sqlalchemy==2.0.23

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]